# Generated by Django 5.1.6 on 2025-08-04 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('aadhaar_photo', models.ImageField(upload_to='ADHAR_CARD/')),
                ('pan_photo', models.ImageField(upload_to='PAN_CARD/')),
                ('bank_passbook_photo', models.ImageField(upload_to='BANK_PASSBOOK/')),
                ('profile_photo', models.ImageField(upload_to='USER_PHOTO')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
