# Generated by Django 5.1.6 on 2025-08-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0002_loanapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='aadhaar_photo',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='bank_passbook_photo',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='pan_photo',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='profile_photo',
        ),
    ]
