# Generated by Django 5.1.6 on 2025-08-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0003_remove_loanapplication_aadhaar_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='aadhaar_photo',
            field=models.ImageField(null=True, upload_to='ADHAR_CARD/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_passbook_photo',
            field=models.ImageField(null=True, upload_to='BANK_PASSBOOK/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='pan_photo',
            field=models.ImageField(null=True, upload_to='PAN_CARD/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='USER_PHOTO/'),
        ),
    ]
