# Generated by Django 5.2.4 on 2025-08-06 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0004_loanapplication_aadhaar_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
