# Generated by Django 5.1.6 on 2025-08-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0005_alter_loanapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='u_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
