# Generated by Django 5.1.6 on 2025-08-06 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0006_customuser_u_name_loanapplication_loan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_type', models.CharField(max_length=50)),
                ('eligibility_status', models.CharField(max_length=20)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
