# Generated by Django 5.1.6 on 2025-08-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0007_loaneligibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='u_name',
            new_name='name',
        ),
    ]
