# Generated by Django 5.1.6 on 2025-08-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0008_rename_u_name_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
