# Generated by Django 5.1.6 on 2025-08-07 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0010_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='name',
            new_name='l_name',
        ),
    ]
