# Generated by Django 5.1.6 on 2025-08-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0012_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
