# Generated by Django 5.1.6 on 2025-08-25 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0013_alter_blogpost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBalence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_used_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('mobile_number', models.CharField(max_length=15)),
                ('pan_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
