# Generated by Django 5.1.6 on 2025-08-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0014_creditbalence_creditscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('credit_score', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
