# Generated by Django 5.1.6 on 2025-08-28 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_api', '0016_credittransaction_delete_creditreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditscore',
            name='email',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='name',
        ),
        migrations.AddField(
            model_name='creditscore',
            name='full_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='loaneligibility',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
